### ISSUE TITLE
有关数据加载

### ISSUE THREAD

**Issue by leizhu1989** [CChBen/GPT2-QA#1]
你好作者，感谢您的开源！有个问题想请教下，看到代码里：
                while words_length - start > cfg.pos_num + 1:
                    self.dataset.append(words[start:start + cfg.pos_num + 1])
                    self.type_num.append(type_words[start:start + cfg.pos_num + 1])
                    start += cfg.stride
                else:
                    if words_length > cfg.pos_num + 1:
                        self.dataset.append(words[words_length - cfg.pos_num - 1:])
                        self.type_num.append(type_words[words_length - cfg.pos_num - 1:])
这个是说明一行百科问题+解答小于pos_num 长度的就不训练了吗，好像小于这个值就不会加载到dataset里面

**Comment by CChBen** [comment]
> 

&nbsp;&nbsp;你好，pos_num指的是位置编码的数量，它的大小也决定了输入数据的字数。

&nbsp;&nbsp;我当时的想法是如果训练的语料字数太少了（小于pos_num），那就要扩充语料字数。如果语料字数很多那就根据pos_num制作多批训练数据跟标签，每批的训练数据跟标签的字数都是pos_num的大小。

&nbsp;&nbsp;当然如果我们的语料字数很大，按照pos_num划分的话，有可能语料字数不能被pos_num等分（即语料的最后一部分的字数不够pos_num）。但是按照上面的逻辑来看，最后一部分的字数小于pos_num是要被丢弃不做数据集的。但实际情况下，这些语料是有用的，所以我才加了else那部分的代码。将语料从最后一个字往前取pos_num个字制作训练数据跟标签。

**Comment by BastianChen** [comment]
> 你好作者，感谢您的开源！有个问题想请教下，看到代码里： while words_length - start > cfg.pos_num + 1: self.dataset.append(words[start:start + cfg.pos_num + 1]) self.type_num.append(type_words[start:start + cfg.pos_num + 1]) start += cfg.stride else: if words_length > cfg.pos_num + 1: self.dataset.append(words[words_length - cfg.pos_num - 1:]) self.type_num.append(type_words[words_length - cfg.pos_num - 1:]) 这个是说明一行百科问题+解答小于pos_num 长度的就不训练了吗，好像小于这个值就不会加载到dataset里面


  &nbsp;&nbsp;你好，pos_num指的是位置编码的数量，它的大小也决定了输入数据的字数。

  &nbsp;&nbsp;我当时的想法是如果训练的语料字数太少了（小于pos_num），那就要扩充语料字数。如果语料字数很多那就根据pos_num制作多批训练数据跟标签，每批的训练数据跟标签的字数都是pos_num的大小。

&nbsp;&nbsp;当然如果我们的语料字数很大，按照pos_num划分的话，有可能语料字数不能被pos_num等分（即语料的最后一部分的字数不够pos_num）。但是按照上面的逻辑来看，最后一部分的字数小于pos_num是要被丢弃不做数据集的。但实际情况下，这些语料是有用的，所以我才加了else那部分的代码。将语料从最后一个字往前取pos_num个字制作训练数据跟标签。

**Comment by leizhu1989** [comment]
明白了，谢谢作者回复；请问您训练的数据是baike_qa_valid吗，还是有疑问，这里面的数据长短不一，有的很短，有的又特别长，模型如果固定长短的话，是如何确保最后问一个简单的问题，想叫他回答短些，难得问题想叫他回答长些具体些的呢，还是这个是由模型决定的呢，模型的输出本身就不是定长

**Comment by BastianChen** [comment]
> 



> 明白了，谢谢作者回复；请问您训练的数据是baike_qa_valid吗，还是有疑问，这里面的数据长短不一，有的很短，有的又特别长，模型如果固定长短的话，是如何确保最后问一个简单的问题，想叫他回答短些，难得问题想叫他回答长些具体些的呢，还是这个是由模型决定的呢，模型的输出本身就不是定长

这个代码是我很早以前写的，时间太久了。所以，是不是baike_qa_valid数据集我已经不记得了。
输出内容的长度不是由模型决定的，是根据特殊字符[END]决定的。当模型输出的内容为[END]特殊字符时，表明此时的输出结束，程序会结束不再输出。另外，每次模型计算后只会输出一个字，可以通过设置模型计算的次数来限制最终输出字数，具体代码可以看detector.py

**Comment by leizhu1989** [comment]
> > 
> 
> > 明白了，谢谢作者回复；请问您训练的数据是baike_qa_valid吗，还是有疑问，这里面的数据长短不一，有的很短，有的又特别长，模型如果固定长短的话，是如何确保最后问一个简单的问题，想叫他回答短些，难得问题想叫他回答长些具体些的呢，还是这个是由模型决定的呢，模型的输出本身就不是定长
> 
> 这个代码是我很早以前写的，时间太久了。所以，是不是baike_qa_valid数据集我已经不记得了。 输出内容的长度不是由模型决定的，是根据特殊字符[END]决定的。当模型输出的内容为[END]特殊字符时，表明此时的输出结束，程序会结束不再输出。另外，每次模型计算后只会输出一个字，可以通过设置模型计算的次数来限制最终输出字数，具体代码可以看detector.py

好的，谢谢作者解答，获益匪浅

**Comment by BastianChen** [comment]
> > > 
> > 
> > 
> > > 明白了，谢谢作者回复；请问您训练的数据是baike_qa_valid吗，还是有疑问，这里面的数据长短不一，有的很短，有的又特别长，模型如果固定长短的话，是如何确保最后问一个简单的问题，想叫他回答短些，难得问题想叫他回答长些具体些的呢，还是这个是由模型决定的呢，模型的输出本身就不是定长
> > 
> > 
> > 这个代码是我很早以前写的，时间太久了。所以，是不是baike_qa_valid数据集我已经不记得了。 输出内容的长度不是由模型决定的，是根据特殊字符[END]决定的。当模型输出的内容为[END]特殊字符时，表明此时的输出结束，程序会结束不再输出。另外，每次模型计算后只会输出一个字，可以通过设置模型计算的次数来限制最终输出字数，具体代码可以看detector.py
> 
> 好的，谢谢作者解答，获益匪浅

不客气

**Comment by leizhu1989** [comment]
还想跟您请教下，baike这个数据里面，对于那些长短不一差异很大的也想拿来训练，我直接在小于pos_num的数据后面加 ‘.’ ，发现训练很久似乎不收敛，loss一直波动，感觉可能是这种扩充语料的办法是不行的。大佬有什么推荐扩充预料的办法吗。baike_qa_train上的数据很多长短不一的，差别非常大，又不想丢掉短的数据

**Comment by BastianChen** [comment]
> 



> 还想跟您请教下，baike这个数据里面，对于那些长短不一差异很大的也想拿来训练，我直接在小于pos_num的数据后面加 ‘.’ ，发现训练很久似乎不收敛，loss一直波动，感觉可能是这种扩充语料的办法是不行的。大佬有什么推荐扩充预料的办法吗。baike_qa_train上的数据很多长短不一的，差别非常大，又不想丢掉短的数据

我记得短的语料跟其他语料可以合并在一起训练的。我当时好像就是把所有的语料放一起训练的，因为每条语料结束的时候最后都会有个END的结束字符。我的理解是模型在训练的时候自注意力能学出来哪些内容属于前一部分语料，哪一些属于后一部分语料，所以一起训练的完没有关系的。当然由于我的硬件资源有限，所以真正很大的数据集有没有问题我也不清楚，我没有训练过，我只是拿了个比较小的数据集训练了下。

**Comment by leizhu1989** [comment]
好的，明白了，非常感谢作者提点

**Comment by leizhu1989** [comment]
发现baike这样的数据不太好训练，每条问答跟前后其他问答的关联不大，感觉混在一起训练会不会有问题。每个batch里面的数据(文字)长度都要相同吧。我能不能把每条问答知识做成一个batch的数据呢，这样是不是训练就会好些，这样感觉每张显卡batchsize都要是1才行吧

**Comment by BastianChen** [comment]
> 发现baike这样的数据不太好训练，每条问答跟前后其他问答的关联不大，感觉混在一起训练会不会有问题。每个batch里面的数据(文字)长度都要相同吧。我能不能把每条问答知识做成一个batch的数据呢，这样是不是训练就会好些，这样感觉每张显卡batchsize都要是1才行吧

我当时就是根据这个仓库里的代码混在一起训练的。在小数据集下效果是可以的，但是我没保存数据集跟权重，现在也没法复现。
但是我觉得也可以像你说的将每条问答只是做成一个batch。但是要做成每个batch的长度相同，不相同的话在算自注意力的时候没法进行矩阵计算。你可以把短的语句后面添加一个统一的特殊字符的索引值，比如：END。
batchsize不一定用1吧，可以再大一些一起训练，每个batch互不影响的，因为这里用的不是batchnorm了，而是layernorm。

**Comment by leizhu1989** [comment]
> > 发现baike这样的数据不太好训练，每条问答跟前后其他问答的关联不大，感觉混在一起训练会不会有问题。每个batch里面的数据(文字)长度都要相同吧。我能不能把每条问答知识做成一个batch的数据呢，这样是不是训练就会好些，这样感觉每张显卡batchsize都要是1才行吧
> 
> 我当时就是根据这个仓库里的代码混在一起训练的。在小数据集下效果是可以的，但是我没保存数据集跟权重，现在也没法复现。 但是我觉得也可以像你说的将每条问答只是做成一个batch。但是要做成每个batch的长度相同，不相同的话在算自注意力的时候没法进行矩阵计算。你可以把短的语句后面添加一个统一的特殊字符的索引值，比如：END。 batchsize不一定用1吧，可以再大一些一起训练，每个batch互不影响的，因为这里用的不是batchnorm了，而是layernorm。

好的，感谢作者提点

**Comment by leizhu1989** [comment]
其实就想叫他生成跟训练时提问的问题，类似的回答就行，但不得不说，想叫GPT生成类似原话还有些难度，语义理解相似性似乎没BERT好

**Comment by BastianChen** [comment]
> 其实就想叫他生成跟训练时提问的问题，类似的回答就行，但不得不说，想叫GPT生成类似原话还有些难度，语义理解相似性似乎没BERT好

你有用过官方的GPT代码跑吗，我这个只是用小数据集跑了下，大的数据集能不能拟合我也不确定，也许针对大数据集有些超参还需要一定的修改才行。
